version: "3"
services:
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    container_name: app
    build: .
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"