okta:
  oauth2:
    issuer: https://car-rest-service.eu.auth0.com/
    audience: https://carapi
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER_CLASS_NAME}
  flyway:
    schemas: car
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_insert: true
csv-file-name: file.csv