okta:
  oauth2:
    issuer: https://car-rest-service.eu.auth0.com/
    audience: https://carapi
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    schemas: car
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_insert: true
csv-file-name: file.csv